### ISSUE TITLE
The train file

### ISSUE THREAD

**Issue by HaFred** [EmbodiedGPT/EmbodiedGPT_Pytorch#4]
Hi, is it possible to provide a sample `train_file`?
https://github.com/EmbodiedGPT/EmbodiedGPT_Pytorch/blob/93bc120974e4c665894852c304381e42a2a63955/align.sh#L28

Thank you very much for open-sourcing this work. Good job!

**Comment by EmbodiedGPT** [comment]
we will provide a example train_file and update the readme document as soon as possible

**Comment by HaFred** [comment]
> we will provide a example train_file and update the readme document as soon as possible

Thank you very much. Before the release, is it possible for you to leave a pointer here for the format of the `train_file`? Like what are the keys `text_file` and `data_name`, etc.? Thanks again.

**Comment by HaFred** [comment]
Thanks for the update @EmbodiedGPT . Could you also release the Ego4D video entries list for https://github.com/EmbodiedGPT/EmbodiedGPT_Pytorch/blob/main/datasets/datasets_share.zip?
Maybe something like this?
![image](https://github.com/EmbodiedGPT/EmbodiedGPT_Pytorch/assets/13991298/147a2e95-9fdc-4b2d-842d-eea6d2994b25)

**Comment by EmbodiedGPT** [comment]
Due to the fact that the original EGO4D videos are not of very high quality and are difficult to store in large volumes, we have gone through several rounds of cleaning, and therefore do not provide an entries list for the original dataset. Data processing from raw data to slicing of video clips to matching of captions can take months, so we offer a simple and easy-to-use version. We provide a video segmentation after 8 keyframes saved as numpy data and text pairs, base version at https://github.com/EmbodiedGPT/EgoCOT_Dataset, full version at https://huggingface.co/datasets/wofmanaf/ego4d-video.

**Comment by HaFred** [comment]
> Due to the fact that the original EGO4D videos are not of very high quality and are difficult to store in large volumes, we have gone through several rounds of cleaning, and therefore do not provide an entries list for the original dataset. Data processing from raw data to slicing of video clips to matching of captions can take months, so we offer a simple and easy-to-use version. We provide a video segmentation after 8 keyframes saved as numpy data and text pairs, base version at https://github.com/EmbodiedGPT/EgoCOT_Dataset, full version at https://huggingface.co/datasets/wofmanaf/ego4d-video.

I see. When I try to load the model at https://drive.google.com/file/d/1sBTy8oXeweJg3STbhzBR_5pLcVs1F20q/view?usp=sharing by running demo/test.py, the model cannot be corrected loaded in at the following line
https://github.com/huggingface/transformers/blob/75b76a5ea461ace0d141d3415879439ae9bbfc22/src/transformers/modeling_utils.py#L533.

Errors: `RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`. I tried to load the bin file directly `torch.load()`, the same error is shown. Would you please check whether the bin files are correctly saved and able to loaded again? Thank you very much.

**Comment by EmbodiedGPT** [comment]
ok Let me check it and when I find the reason, I will update all the related files as soon as possible.  I will review the entire section of the repo to ensure it operates correctly. This process will take some time, as some data and models are quite large and will require a while to upload. I will update as soon as possible.

**Comment by EmbodiedGPT** [comment]
When it is ready, I will tell you as soon as possible. Thanks for your great effort and support to this project.

**Comment by HaFred** [comment]
Another thing is about the video file as well. The `z01` file [here](https://huggingface.co/datasets/wofmanaf/ego4d-video/tree/main) seems to be unable to unzip, isn't it supposed to be at least a `zip` file here to unzip?
* https://en.bandisoft.com/bandizip/howto/open-z01/

Yes, I totally get that open-sourcing the code is tedious. Thank you very much for your efforts!

**Comment by EmbodiedGPT** [comment]
Ok let me check it, it may be caused by the error of the uploading process

**Comment by wofmanaf** [comment]
> Another thing is about the video file as well. The `z01` file [here](https://huggingface.co/datasets/wofmanaf/ego4d-video/tree/main) seems to be unable to unzip, isn't it supposed to be at least a `zip` file here to unzip?
> 
> * https://en.bandisoft.com/bandizip/howto/open-z01/
> 
> Yes, I totally get that open-sourcing the code is tedious. Thank you very much for your efforts!

Some files uploaded failed, we will reupload them, there are a total of 52 files, about 526G. Please wait for half a day or so until the files are ready.
![ego4d_video](https://github.com/EmbodiedGPT/EmbodiedGPT_Pytorch/assets/15992442/add16814-5eae-4648-8ca7-c77a3d2406f4)
